---
title: "Narrative"
author: "Gaegoung Kim"
date: "12/09/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Brief substantive background / goal
My goal is to analyze the sentiment on the issue of trade in 2016 presidential campaign speeches. I use speeches by Hilary Clinton, Bernie Sanders and Donald Trump.

## Collecting data
I collected data by scraping presidential campaign speeches from the web(https://www.presidency.ucsb.edu)

## Cleaning / pre-processing data
Once I collected the data by webscraping, I subset the data to only include years 2015 and 2016 since I am only interested in the speeches from the 2016 presidential election.

## Analysis and visualization
In Part I, I scrape presidential campaign speeches by 3 candidates - Hilary Clinton, Bernie Sanders and Donald Trump - from web(https://www.presidency.ucsb.edu). Since some of the candidates ran for presidential election multiple times, I subset the data to only include years 2015 and 2016. Since I am interested in looking at the sentiment specific to trade issues, I extract paragraphs that contain the word "trade" and create a separate dataframe.

In Part II, I execute sentiment analysis on the paragraphs that contain the word "trade" and look at how the sentiment varies by presidential candidates. Here, I was curious whether the outcome varies according to the type of sentiment dictionary I use, so I try sentiment analysis using three different dictionaries - bing, afinn, loughran. I assign the value 1 for positive words, -1 for negative words, and 0 for words not in the dictionary and find the mean sentiment score by president for each dictionary.

In Part III, I use bar graphs to compare my results from Part II. In addition, unlike other dictionaries that I use - which only tell you whether a word is positive or negative - the dictionary "afinn" indicate the strengths of sentiment (how positive or negative a word is) on a scale of -3 to 3. I assign "strongly negative" to -3, "negative" to -2 and so on and count how many words used in the 2016 presidential campaign speeches by the three candidates (again, this is limited to paragraphs that contain the word "trade") fit into each of these sentiment categories. I show the result using a bar graph.

## Future work
Future work could include a time-series analysis of how sentiment on the issue of trade varies over time.
